[package]
name = "ceres-core"
version = "0.1.2"
authors = ["mori"]
edition = "2018"

[dependencies]
pest = "~2.1"
rlua = "~0.16"
log = "~0.4"
matches = "~0.1"
failure = "~0.1"
fs_extra = "~1.1"
serde = {version = "~1.0", features = ["derive"]}
toml = "~0.5"
indexmap = "~1.0"

#ceres-mpq = {path = "../ceres-mpq"}
ceres-parsers = {path = "../ceres-parsers"}