[package]
name = "storm-sys"
version = "0.1.0"
authors = ["mori"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.49.2"
cc = { version = "1.0.37", features = ["parallel"] }
