[package]
name = "ceres-binaries"
version = "0.2.0"
authors = ["mori"]
edition = "2018"

[dependencies]
ceres-parsers = {path = "../ceres-parsers"}
ceres-core = {path = "../ceres-core"}

pest = "2.1.1"
rlua = "0.16.3"

[dependencies.clap]
version = "2.33.0"
default-features = false
